name: Docker Image CI

on:
  push:
    branches: [ "main", "ci-test" ]
  pull_request:
    branches: [ "main", "ci-test", "tt08", "tt09" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker base image
      run: docker build -t ol2-base -f docker/base.dockerfile .
    - name: Build the Docker main image
      run: docker build -t ol2-main -f docker/ol2.dockerfile .
